### ISSUE TITLE
TypeError: Failed to fetch error in Promise.race function in chrome.js

### ISSUE THREAD

**Issue by white-b1nary** [MoroccanTea/PhishMeNot#12]
### Bug description 
The extension is throwing a **"TypeError: Failed to fetch"** error in chrome.js _on line 39_. This error occurs when the fetchPromise in the Promise.race function fails.

### To Reproduce Steps to reproduce the behavior:

Install the extension in Google Chrome.
Navigate to any webpage.
Right-click and select "Analyze URL" from the context menu.
Open the console (Ctrl+Shift+J on Windows/Linux, Command+Option+J on Mac).
See the "TypeError: Failed to fetch" error.

_Expected behavior The extension should successfully fetch the data without throwing any errors._

Desktop (Lenovo Thinkbook 13s):

OS: [Windows 11 Entreprise]
Browser: Chrome
Version: [118.0.5993.120 (Build officiel) (64 bits)]

### Additional context

The error seems to be related to the fetchPromise. It might be due to a network issue, a problem with the URL, or a CORS issue. Further investigation is needed to determine the exact cause.

**Comment by MoroccanTea** [comment]
I don't think this bug is up to date, it might be fixed...
