### ISSUE TITLE
Auth: En tant qu'utilisateur je veux me connecter ou m'inscrire avec mon compte google

### ISSUE THREAD

**Issue by t-idriss** [MoroccanTea/PhishMeNot#15]
**En tant qu'utilisateur je veux me connecter ou m'inscrire avec mon compte google**
* l'utilisateur ouvre l'extension
* Si l'utilisateur n'est pas connecter il est rediriger sur la page authentication
* L'utilisateur clique sur le bouton "Auth"
* L'utilisateur est connecté ou inscrite avec son compte google
* L'utilisateur accede a son dashboard

**Comment by MoroccanTea** [comment]
Cette fonctionnalité a été implémentée au niveau backend @t-idriss, Il faut juste le front et les calls APIs

**Comment by t-idriss** [comment]
@MoroccanTea d'accord je vais push et implémenté l'appel

**Comment by MoroccanTea** [comment]
![image](https://github.com/MoroccanTea/PhishMeNot/assets/58166226/93a76584-a10f-44a0-9b30-d378ecd42e85)
