### ISSUE TITLE
Notification en temps réel pour les sites détectés

### ISSUE THREAD

**Issue by felestini12** [MoroccanTea/PhishMeNot#28]
**Informez immédiatement l'utilisateur lorsqu'un site potentiellement dangereux est détecté.**

**Comment by felestini12** [comment]
![information sur le site](https://github.com/MoroccanTea/PhishMeNot/assets/101877045/5a7ccbc5-9e93-40e2-85e8-0b3e0adb84a2)
![message pop up](https://github.com/MoroccanTea/PhishMeNot/assets/101877045/4126c325-a3f4-4dac-b4de-0cb8be0f6a9f)

**Comment by MoroccanTea** [comment]
Duplicate of an existing issue #18 , that is already assigned to @white-b1nary
