### ISSUE TITLE
En tant qu'utilisateur je veux pouvoir consulter les stats de ma navigation

### ISSUE THREAD

**Issue by white-b1nary** [MoroccanTea/PhishMeNot#30]
- En tant qu'utilisateur je veux pouvoir consulter les différents statistiques

**Comment by azhbbx3** [comment]
je peut voir l'intégrité du lien
je doit être informé si le site est du phishing
je doit avoir un systeme de score sur chaque site ( quels sont les chances que le site est un phishing website, ou un clean safe website)
je doit être informé de la dernière fois l'extension a scanné mon email, et si c'est securisé ou pas
je doit avoir des statistiques sur le numero de sites web visités, y inclus le nombre de sites web safe, malicieux, backlistés, et whitelistés
je doit avoir l'option de trier cette invormation par mois, semaine, jour, heure, et année

**Comment by MoroccanTea** [comment]
Duplicate of issue #16, refer to that issue if you want to contribute.
